# ile wierszy wczytać z raw_df (None = wszystko)
sample_n: null

# kolumna celu
target_col: "Satisfaction"

split:
  test_size: 0.2
  random_state: 42
  stratify: true

model:
  kind: "logreg"
  max_iter: 5000
  C: 1.0
  random_state: 42
