_wandb:
    value:
        cli_version: 0.22.3
        e:
            ox7w5o4xlhfe5vk0g86nd3nrtkkdg4dj:
                args:
                    - -q
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "511078113280"
                        used: "356777635840"
                email: sadej.jan1@gmail.com
                executable: C:\Users\uniaw\anaconda3\envs\asi-ml\python.exe
                git:
                    commit: ab8a75ccd804d1cacd0c4bf986fe6d956e26a276
                    remote: https://github.com/Dzzzuma/Asi2025
                host: DESKTOP-5FMQQBC
                memory:
                    total: "17010921472"
                os: Windows-10-10.0.26200-SP0
                program: -m __main__
                python: CPython 3.11.14
                root: C:\Users\uniaw\Asi2025
                startedAt: "2025-10-30T19:54:20.458055Z"
                writerId: ox7w5o4xlhfe5vk0g86nd3nrtkkdg4dj
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.11.14
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
kind:
    value: logreg
max_iter:
    value: 5000
