_wandb:
    value:
        cli_version: 0.22.3
        e:
            o8v7rmoyv35hm6aucbrwzx9hj25zgqhe:
                args:
                    - run
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "511078113280"
                        used: "356775174144"
                email: sadej.jan1@gmail.com
                executable: C:\Users\uniaw\anaconda3\envs\asi-ml\python.exe
                git:
                    commit: f5ce0b8779654c7cfe665bbaf7d35971e2170e1a
                    remote: https://github.com/Dzzzuma/Asi2025
                host: DESKTOP-5FMQQBC
                memory:
                    total: "17010921472"
                os: Windows-10-10.0.26200-SP0
                program: -m __main__
                python: CPython 3.11.14
                root: C:\Users\uniaw\Asi2025
                startedAt: "2025-10-30T19:38:24.800186Z"
                writerId: o8v7rmoyv35hm6aucbrwzx9hj25zgqhe
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.11.14
            "5": 0.22.3
            "8":
                - 3
            "10":
                - 20
            "12": 0.22.3
            "13": windows-amd64
